ss_admin_console/main/default/objects/Toggle__mdt/Toggle__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to store all of our toggles for data manipulation.</description>
    <label>Toggle</label>
    <pluralLabel>Toggles</pluralLabel>
</CustomObject>

ss_admin_console/main/default/objects/Toggle__mdt/fields/ProductionOrgToggle__c.field-meta.xml
<CustomField>
    <fullName>ProductionOrgToggle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This toggle controls appearance of &quot;Data Loading&quot; item in the drop down list based upon TRUE/FALSE</description>
    <label>Production Org Toggle</label>
    <type>Checkbox</type>
</CustomField>

ss_admin_console/main/default/classes/AllAboutCustomMetadata.cls
public with sharing class AllAboutCustomMetadata {
    public AllAboutCustomMetadata() {

    }
    public static void fetchAllMetadata(){
        Map<String, Toggle__mdt>allToggles = Toggle__mdt.getAll();
        System.debug('allToggles Value: ' + allToggles.size());
    }

    public static void fetchProductionOrgToggle(){
        Toggle__mdt productionOrgToggle = Toggle__mdt.getInstance('ProductionOrgToggle');
        System.debug('Production Org Toggle value: ' + productionOrgToggle.ProductionOrgToggle__c);
    }

    public static Boolean getProductionOrgToggle(){
        Toggle__mdt productionOrgToggle = Toggle__mdt.getInstance('ProductionOrgToggle');
        return productionOrgToggle.ProductionOrgToggle__c;
    }

}