ss_admin_console/main/default/objects/Job_Setting__mdt/Job_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Job Setting</label>
    <pluralLabel>Job Settings</pluralLabel>
</CustomObject>

ss_admin_console/main/default/objects/Job_Setting__mdt/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <label>Job Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ss_admin_console/main/default/classes/actions/SSACBatchableAction.cls
public with sharing class SSACBatchableAction implements ISSACAction {

    private String className;
    private SSACLogger logger;

    public SSACBatchableAction(String className) {
        this.className = className;
        this.logger = new SSACLogger();
    }

    public List<SSACResult> test() {
        Job_Setting__mdt setting = new SSACUtil().getJobSetting(SSACConstants.SIZE_JOB_NAME);
        if (setting == null || setting.Job_Size__c == null) {
           this.generateEmptyBatchSizeLog();
        } else {
            this.logger.publishLog('Job ' + this.className + ' can be run, batch size is: ' + setting.Job_Size__c,
                    'You can change batch size Job Setting custom metadata',
                    SSACConstants.OK_STATUS);
        }
        return new List<SSACResult>();
    }

    public List<SSACResult> execute() {
        Job_Setting__mdt setting = new SSACUtil().getJobSetting(SSACConstants.SIZE_JOB_NAME);
        if (setting == null || setting.Job_Size__c == null) {
            this.generateEmptyBatchSizeLog();
        } else {
            try {
                Id batchJobId = Database.executeBatch((Database.Batchable<SObject>)(Type.forName(this.className).newInstance()),
                        Integer.valueOf(setting.Job_Size__c));
                this.logger.publishLog('Job ' + this.className + ' was successfully run',
                        'Job id: ' + batchJobId,
                        SSACConstants.OK_STATUS);
            } catch(Exception ex) {
                this.logger.publishLog('Error for run ' + this.className,
                        'Error occurred: ' + ex.getMessage(), SSACConstants.FAILED_STATUS);
            }
        }
        return new List<SSACResult>();
    }

    private void generateEmptyBatchSizeLog() {
        this.logger.publishLog('Error for batchable ' + this.className,
                'Error occurred: Job size is empty, ' +
                        'please fill in job sine in Job Setting custom metadata: Job Size', Constants.FAILED_STATUS);
    }
}