ss_admin_console/main/default/objects/ResultLogEvent__e/ResultLogEvent__e.object-meta.xml
<CustomObject>
    <label>ResultLogEvent</label>
    <pluralLabel>ResultLogEvents</pluralLabel>
</CustomObject>

ss_admin_console/main/default/objects/ResultLogEvent__e/fields/Action_Completed__c.field-meta.xml
<CustomField>
    <fullName>Action_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Action Completed</label>
    <type>Checkbox</type>
</CustomField>

ss_admin_console/main/default/objects/ResultLogEvent__e/fields/Action_Message__c.field-meta.xml
<CustomField>
    <fullName>Action_Message__c</fullName>
    <label>Action Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/objects/ResultLogEvent__e/fields/Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Action_Name__c</fullName>
    <label>Action Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/objects/ResultLogEvent__e/fields/Action_Status__c.field-meta.xml
<CustomField>
    <fullName>Action_Status__c</fullName>
    <label>Action Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/objects/ResultLogEvent__e/fields/Action_Title__c.field-meta.xml
<CustomField>
    <fullName>Action_Title__c</fullName>
    <label>Action Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/objects/ResultLogEvent__e/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <label>Action Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/objects/SObjectLoadEvent__e/SObjectLoadEvent__e.object-meta.xml
<CustomObject>
    <label>SObjectLoadEvent</label>
    <pluralLabel>SObjectLoadEvents</pluralLabel>
</CustomObject>

ss_admin_console/main/default/objects/SObjectLoadEvent__e/fields/Message_Title__c.field-meta.xml
<CustomField>
    <fullName>Message_Title__c</fullName>
    <label>Message Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/objects/SObjectLoadEvent__e/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ss_admin_console/main/default/classes/poc/logger/PlatformEventFeedLogger.cls
public with sharing class PlatformEventFeedLogger implements FeedLogger {

    //TODO error to event
    public void error(String messageError) {
        System.debug('messageError: ' + messageError);
    }

    public void log(String messageTitleLog, String messageLog, String statusLog) {
        SObjectLoadEvent__e event = new SObjectLoadEvent__e(
                Message_title__c = messageTitleLog,
                Message__c = messageLog,
                Message_Type__c = statusLog
        );
        EventBus.publish(event);
    }

    public void publishResultLog(String jobName, String jobAction) {
        ResultLogEvent__e event = new ResultLogEvent__e(Action_Name__c = jobName, Action_Completed__c = true, Action_Type__c = jobAction);
        EventBus.publish(event);
    }

    public void publishLog(String title, String message, String status) {
        ResultLogEvent__e event = new ResultLogEvent__e(Action_Message__c = message, Action_Title__c = title, Action_Status__c = status);
        EventBus.publish(event);
    }
}